''' This file declares all the constants being used to send the email
'''
SENDER_EMAIL = "enhancedcwe@gmail.com"
REPORT_ACCEPTED_SUBJECT = "Your Report has been accepted"
REPORT_APPROVED_SUBJECT = "A report has been reviewed and approved"
ACCEPTED = "accepted"
REVIEWER = "reviewer"
REJECTED = "rejected"
APPROVED = "approved"
COMMENTED = "comment"
REPORT_REJECTED_SUBJECT = "Your Report has been rejected"
REPORT_COMMENTED_SUBJECT = "Your Report has been commented"
REPORT_SUBMITTED_FOR_REVIEW_SUBJECT = "A Report has been submitted for review"
REPORT_INAPPROPRIATE_SUBJECT = "Your Report has been marked as Inappropriate"
SUBMITTED = "submitted"
CREATED = "created"
INAPPROPRIATE = "inappropriate"
